/*
 * CadastroUsuario1.java
 *
 * Created on 14 de Setembro de 2011, 21:57
 */
package br.com.gecel.view;

import br.com.gecel.control.Conexao;
import br.com.gecel.dao.UsuarioDAO;
import br.com.gecel.exception.CreateDAOException;
import br.com.gecel.model.entity.Privilegio;
import br.com.gecel.model.entity.Usuario;
import java.awt.AWTKeyStroke;
import java.awt.Color;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Familia-Silva
 */
public class CadastroUsuario extends javax.swing.JFrame {

  private Conexao connect;
  String foto;

  /**
   * Creates new form CadastroUsuario1
   */
  public CadastroUsuario() {
    initComponents();

    setResizable(false);
    connect = new Conexao();
    enter();
  }

  public void enter() {
// Enter simula tecla Tab
    HashSet conj = new HashSet(getFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS));
    conj.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_ENTER, 0));
    setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, conj);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        txtlogin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtsenha = new javax.swing.JTextField();
        btnsair = new java.awt.Button();
        btncadastrar = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Usuário");
        getContentPane().setLayout(null);

        jLabel4.setText("Usuário");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 20, 60, 14);
        getContentPane().add(txtusuario);
        txtusuario.setBounds(80, 20, 170, 20);
        getContentPane().add(txtlogin);
        txtlogin.setBounds(80, 50, 170, 20);

        jLabel1.setText("Login");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 52, 60, 14);

        jLabel2.setText("Senha");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 81, 60, 14);
        getContentPane().add(txtsenha);
        txtsenha.setBounds(80, 80, 170, 20);

        btnsair.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnsair.setLabel("Sair");
        btnsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsairActionPerformed(evt);
            }
        });
        getContentPane().add(btnsair);
        btnsair.setBounds(170, 120, 80, 30);

        btncadastrar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btncadastrar.setLabel("Cadastrar");
        btncadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btncadastrar);
        btncadastrar.setBounds(80, 120, 80, 30);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-276)/2, (screenSize.height-188)/2, 276, 188);
    }// </editor-fold>//GEN-END:initComponents

    private void btncadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadastrarActionPerformed

      if (txtusuario.getText().equals("")
              || txtlogin.getText().equals("")
              || txtsenha.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "Campos obrigatórios.");
        txtusuario.setBackground(Color.yellow);
        txtlogin.setBackground(Color.yellow);
        txtsenha.setBackground(Color.yellow);
      } else {
        try {
          foto = txtusuario.getText().replace(" ", "");

          Usuario usuario = new Usuario(txtusuario.getText(), txtlogin.getText(), txtsenha.getText(),
                  "C:/Arquivos de programas/Fotos/".concat(foto.concat(".jpg")), 1, new Privilegio(1));

          UsuarioDAO usuarioDAO = new UsuarioDAO();

          usuarioDAO.incluirUsuario(usuario);
          JOptionPane.showMessageDialog(null, "Usuário cadastrado com sucesso.");
          limpaCampos();
        } catch (CreateDAOException ex) {
          Logger.getLogger(CadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
          Logger.getLogger(CadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
      }

    }//GEN-LAST:event_btncadastrarActionPerformed
  public void limpaCampos() {
    txtusuario.setBackground(Color.white);
    txtlogin.setBackground(Color.white);
    txtsenha.setBackground(Color.white);
    txtusuario.setText("");
    txtlogin.setText("");
    txtsenha.setText("");
    txtusuario.requestFocus();
  }
    private void btnsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsairActionPerformed
      dispose();
    }//GEN-LAST:event_btnsairActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {

      public void run() {
        new CadastroUsuario().setVisible(true);
      }
    });
  }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btncadastrar;
    private java.awt.Button btnsair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtlogin;
    private javax.swing.JTextField txtsenha;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
