/*
 * CadastroContato.java
 *
 * Created on 6 de Outubro de 2011, 08:51
 */
package br.com.gecel.view;

import br.com.gecel.util.Validacao;
import br.com.gecel.control.Conexao;
import br.com.gecel.dao.ContatoDAO;
import br.com.gecel.dao.LoginDAO;
import br.com.gecel.dao.ParticipanteDAO;
import br.com.gecel.exception.CreateDAOException;
import br.com.gecel.model.entity.Contato;
import br.com.gecel.model.entity.Endereco;
import br.com.gecel.model.entity.Participante;
import br.com.gecel.model.entity.Usuario;
import br.com.gecel.jmf.ConfiguraProcessor;
import br.com.gecel.jmf.GerenteJMF;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Familia-Silva
 */
public class CadastroAluno extends javax.swing.JFrame {
    //private static conexao b;

    private int numeroRegistros = 0;
    MaskFormatter FormatoData, FormatoCpf, FormatoCnpj,
            FormatoCep, FormatoTel1, FormatoTel2;
    Login login;
    Conexao connect;
    LoginDAO loginDAO;
    ParticipanteDAO participanteDAO;
    String foto;
    String sexo;
    Integer idParcipamente;
    private static final long serialVersionUID = 2769157269484182163L;
    private GerenteJMF gerente;
    private Component pnlVideo;
    private JButton btnAcionarFoto;
    

    /**
     * Creates new form CadastroContato
     */
    public CadastroAluno() throws SQLException {
        initComponents();
        //lblimagem.setIcon(new ImageIcon(Login.imagem.getText()));
        connect = new Conexao();
        id.setVisible(false);
        try {
           this.inicializarJMF();//inicializa o jmf
            //   this.getContentPane().add(getBotaoFoto());//adiciona no container principal o botao
        } catch (Exception e) {
            e.printStackTrace();
        }

        this.setLayout(null);//altera o layout para null
        //this.setSize(390, 270);//ajusta o tamanho da janela
        this.setLocationRelativeTo(null);//centralizar o jframe na tela
        this.setVisible(true);//torna o jframe visivel
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtsobrenome = new javax.swing.JTextField();
        try
        {
            FormatoTel1 = new MaskFormatter("(##)####-####");
        }
        catch (Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possível gerar máscara, erro = " +erro);
        }

        ftxttel = new JFormattedTextField (FormatoTel1);
        try
        {
            FormatoTel1 = new MaskFormatter("(##)####-####");
        }
        catch (Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possível gerar máscara, erro = " +erro);
        }

        ftxtcel = new JFormattedTextField (FormatoTel1);
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        try
        {
            FormatoCep = new MaskFormatter("##.###-###");
        }
        catch (Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possível gerar máscara, erro = " +erro);
        }

        ftxtcep = new JFormattedTextField (FormatoCep);
        txtlogradouro = new javax.swing.JTextField();
        txtbairro = new javax.swing.JTextField();
        txtcomplemento = new javax.swing.JTextField();
        txtcidade = new javax.swing.JTextField();
        txtuf = new javax.swing.JTextField();
        txtnumero = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btncadastrar = new java.awt.Button();
        btnlimpar = new java.awt.Button();
        jPanel2 = new javax.swing.JPanel();
        btnsair = new java.awt.Button();
        txtnome = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        try
        {
            FormatoData = new MaskFormatter("##/##/####");
        }
        catch (Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possível gerar máscara, erro = " +erro);
        }

        ftxtnascimento = new JFormattedTextField (FormatoData);
        cmbcurso = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();

        txtmatricula = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        cmbsexo = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        txtprojeto = new javax.swing.JTextField();
        txtrg = new javax.swing.JTextField();
        lblnome3 = new javax.swing.JLabel();
        try
        {
            FormatoCpf = new MaskFormatter("###.###.###-##");
        }
        catch (Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possível gerar máscara, erro = " +erro);
        }

        ftxtcpf = new JFormattedTextField (FormatoCpf);
        lblnome5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtobs = new javax.swing.JTextField();
        id = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Contato");
        setIconImages(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));
        jPanel1.setLayout(null);

        jLabel2.setText("Sobrenome");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 87, 70, 14);

        txtsobrenome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsobrenomeKeyReleased(evt);
            }
        });
        jPanel1.add(txtsobrenome);
        txtsobrenome.setBounds(110, 80, 240, 20);

        ftxttel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftxttelFocusLost(evt);
            }
        });
        ftxttel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ftxttelKeyReleased(evt);
            }
        });
        jPanel1.add(ftxttel);
        ftxttel.setBounds(110, 160, 100, 20);
        jPanel1.add(ftxtcel);
        ftxtcel.setBounds(251, 160, 100, 20);

        jLabel4.setText("Tel.");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 167, 34, 14);

        jLabel5.setText("Email");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 326, 50, 14);
        jPanel1.add(txtemail);
        txtemail.setBounds(110, 320, 170, 20);

        jLabel7.setText("C.E.P");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 365, 34, 14);

        ftxtcep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftxtcepFocusLost(evt);
            }
        });
        ftxtcep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ftxtcepKeyReleased(evt);
            }
        });
        jPanel1.add(ftxtcep);
        ftxtcep.setBounds(110, 360, 100, 20);

        txtlogradouro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtlogradouroKeyReleased(evt);
            }
        });
        jPanel1.add(txtlogradouro);
        txtlogradouro.setBounds(300, 360, 320, 20);

        txtbairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbairroKeyReleased(evt);
            }
        });
        jPanel1.add(txtbairro);
        txtbairro.setBounds(290, 400, 150, 20);
        jPanel1.add(txtcomplemento);
        txtcomplemento.setBounds(110, 400, 130, 20);

        txtcidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcidadeKeyReleased(evt);
            }
        });
        jPanel1.add(txtcidade);
        txtcidade.setBounds(500, 400, 190, 20);

        txtuf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtufKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtufKeyTyped(evt);
            }
        });
        jPanel1.add(txtuf);
        txtuf.setBounds(720, 400, 30, 20);

        txtnumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnumeroKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnumeroKeyTyped(evt);
            }
        });
        jPanel1.add(txtnumero);
        txtnumero.setBounds(660, 360, 90, 20);

        jLabel8.setText("Logradouro");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(225, 365, 70, 14);

        jLabel9.setText("Nº");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(632, 365, 30, 14);

        jLabel10.setText("Complemento");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 405, 80, 14);

        jLabel11.setText("Bairro");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(250, 405, 50, 14);

        jLabel12.setText("Cidade");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(450, 405, 50, 14);

        jLabel13.setText("UF");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(700, 405, 30, 14);

        jLabel14.setText("Cel.");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(223, 167, 34, 14);

        btncadastrar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btncadastrar.setLabel("Cadastrar");
        btncadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(btncadastrar);
        btncadastrar.setBounds(20, 440, 80, 30);

        btnlimpar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnlimpar.setLabel("Limpar");
        btnlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimparActionPerformed(evt);
            }
        });
        jPanel1.add(btnlimpar);
        btnlimpar.setBounds(130, 440, 80, 30);

        jPanel2.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jPanel2ComponentAdded(evt);
            }
        });
        jPanel2.setLayout(null);
        jPanel1.add(jPanel2);
        jPanel2.setBounds(360, 30, 390, 270);

        btnsair.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnsair.setLabel("Sair");
        btnsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsairActionPerformed(evt);
            }
        });
        jPanel1.add(btnsair);
        btnsair.setBounds(240, 440, 80, 30);

        txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeActionPerformed(evt);
            }
        });
        txtnome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnomeKeyReleased(evt);
            }
        });
        jPanel1.add(txtnome);
        txtnome.setBounds(110, 40, 240, 20);

        jLabel15.setText("Nome");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(20, 50, 34, 14);

        ftxtnascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ftxtnascimentoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftxtnascimentoFocusLost(evt);
            }
        });
        ftxtnascimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ftxtnascimentoKeyReleased(evt);
            }
        });
        jPanel1.add(ftxtnascimento);
        ftxtnascimento.setBounds(110, 120, 110, 20);

        cmbcurso.setMaximumRowCount(4);
        cmbcurso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Curso", "ADM", "Ciências Contábeis", "Enfermagem", "Pedagogia", "Sistema de Informação", "Turismo" }));
        cmbcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcursoActionPerformed(evt);
            }
        });
        cmbcurso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmbcursoKeyReleased(evt);
            }
        });
        jPanel1.add(cmbcurso);
        cmbcurso.setBounds(190, 200, 160, 20);

        jLabel16.setText("Nasc.");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(20, 127, 34, 14);

        txtmatricula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtmatriculaFocusLost(evt);
            }
        });
        txtmatricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmatriculaKeyReleased(evt);
            }
        });
        jPanel1.add(txtmatricula);
        txtmatricula.setBounds(110, 200, 70, 20);

        jLabel17.setText("Matrícula");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(20, 210, 60, 14);

        cmbsexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sexo", "Masculino", "Feminino" }));
        cmbsexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbsexoActionPerformed(evt);
            }
        });
        cmbsexo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmbsexoKeyReleased(evt);
            }
        });
        jPanel1.add(cmbsexo);
        cmbsexo.setBounds(240, 120, 110, 20);

        jLabel18.setText("Projeto");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(20, 250, 50, 14);

        txtprojeto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtprojetoKeyReleased(evt);
            }
        });
        jPanel1.add(txtprojeto);
        txtprojeto.setBounds(110, 240, 240, 20);
        jPanel1.add(txtrg);
        txtrg.setBounds(110, 280, 90, 20);

        lblnome3.setText("RG");
        jPanel1.add(lblnome3);
        lblnome3.setBounds(20, 286, 60, 14);

        ftxtcpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftxtcpfFocusLost(evt);
            }
        });
        jPanel1.add(ftxtcpf);
        ftxtcpf.setBounds(250, 280, 100, 20);

        lblnome5.setText("CPF");
        jPanel1.add(lblnome5);
        lblnome5.setBounds(210, 286, 80, 14);

        jLabel6.setText("Observação");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(295, 326, 110, 14);
        jPanel1.add(txtobs);
        txtobs.setBounds(370, 320, 380, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 20, 762, 480);

        id.setText("jLabel1");
        getContentPane().add(id);
        id.setBounds(20, 4, 90, 20);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-789)/2, (screenSize.height-544)/2, 789, 544);
    }// </editor-fold>//GEN-END:initComponents

    private JButton getBotaoFoto() {

        if (btnAcionarFoto == null) {

            btnAcionarFoto = new JButton("Capturar");
            btnAcionarFoto.setBounds(120, 260, 90, 25);

            /*
             * Associa o evento do bot�o salvar o ato de salvar a foto na maquina 
             */
            btnAcionarFoto.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent arg0) {
                    try {
                        gerente.salvarFoto();
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            });

        }

        return btnAcionarFoto;
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//// coloca uma figura na barra de título da janela  
//URL url = this.getClass().getResource("/br/com/gecel/imagem/ana.jpg");  
//Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);  
//this.setIconImage(imagemTitulo);  
        //        try {
//// TODO add your handling code here:
//            txtcodigo.setText(String.valueOf(b.queryCodiContato()));
//        } catch (SQLException ex) {
//            ex.printStackTrace();
//        }
        //this.setExtendedState(this.MAXIMIZED_BOTH);
        // this.setUndecorated(true);  
        //this.getRootPane().setWindowDecorationStyle(JRootPane.FRAME); 
//      try {
//        id.setText(String.valueOf(new LoginDAO().consultaParticipante()));
//        System.out.println("id Participante " + idParcipamente);
//
//      } catch (SQLException ex) {
//        Logger.getLogger(CadastroAluno.class.getName()).log(Level.SEVERE, null, ex);
//      } catch (CreateDAOException ex) {
//        Logger.getLogger(CadastroAluno.class.getName()).log(Level.SEVERE, null, ex);
//      }
    }//GEN-LAST:event_formWindowOpened
    private void inicializarJMF() throws Exception {

        gerente = new GerenteJMF();
        pnlVideo = gerente.getPainelVideo();
        pnlVideo.setBounds(10, 10, 390, 270);
        //this.getContentPane().add(pnlVideo);
        jPanel2.add(pnlVideo);

    }
    private void btnsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsairActionPerformed
        try {
            dispose();
            gerente.removePlayerVideo();
           // hide();
        } catch (Exception ex) {
            Logger.getLogger(CadastroAluno.class.getName()).log(Level.SEVERE, null, ex);
        }
              
        
    }//GEN-LAST:event_btnsairActionPerformed

    private void btnlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimparActionPerformed

        limpaCampos();

    }//GEN-LAST:event_btnlimparActionPerformed
    public void limpaCampos() {
        txtnome.setBackground(Color.white);
        txtsobrenome.setBackground(Color.white);
        ftxttel.setBackground(Color.white);
        ftxtcep.setBackground(Color.white);
        txtbairro.setBackground(Color.white);
        txtlogradouro.setBackground(Color.white);
        txtcidade.setBackground(Color.white);
        txtuf.setBackground(Color.white);
        txtnumero.setBackground(Color.white);
        txtprojeto.setBackground(Color.white);
        txtemail.setBackground(Color.white);
        txtobs.setBackground(Color.white);
        txtmatricula.setBackground(Color.white);
        ftxtnascimento.setBackground(Color.white);
        cmbcurso.setBackground(Color.white);
        cmbsexo.setBackground(Color.white);

        txtmatricula.setText("");
        txtemail.setText("");
        txtobs.setText("");
        txtprojeto.setText("");
        ftxtnascimento.setText("");
        txtsobrenome.setText("");
        ftxttel.setText("");
        ftxtcel.setText("");
        ftxtcep.setText("");
        txtbairro.setText("");
        txtlogradouro.setText("");
        txtcidade.setText("");
        txtuf.setText("");
        txtnumero.setText("");
        txtnome.setText("");
        txtcomplemento.setText("");
        txtrg.setText("");
        txtnome.requestFocus();
        cmbcurso.setSelectedIndex(0);
        cmbsexo.setSelectedIndex(0);
        ftxtcpf.setValue("");
    }
    private void btncadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadastrarActionPerformed
// TODO add your handling code here:

        //  numeroRegistros = Integer.parseInt(id.getText());

        if (txtsobrenome.getText().equals("")
                || ftxtnascimento.getText().equals("")
                || txtnome.getText().equals("")
                || ftxttel.getText().equals("")
                || ftxtcep.getText().equals("")
                || txtbairro.getText().equals("")
                || txtlogradouro.getText().equals("")
                || txtprojeto.getText().equals("")
                || txtmatricula.getText().equals("")
                || txtcidade.getText().equals("")
                || txtuf.getText().equals("")
                || txtnumero.getText().equals("")) {

            JOptionPane.showMessageDialog(null,
                    "Campo obrigatário");
            ftxtnascimento.setBackground(Color.yellow);
            txtnome.setBackground(Color.yellow);
            txtprojeto.setBackground(Color.yellow);
            txtmatricula.setBackground(Color.yellow);
            txtsobrenome.setBackground(Color.yellow);
            ftxttel.setBackground(Color.yellow);
            ftxtcep.setBackground(Color.yellow);
            txtbairro.setBackground(Color.yellow);
            txtlogradouro.setBackground(Color.yellow);
            txtcidade.setBackground(Color.yellow);
            txtuf.setBackground(Color.yellow);
            txtnumero.setBackground(Color.yellow);

        } else if (cmbcurso.getSelectedItem().equals("Curso")
                || cmbsexo.getSelectedItem().equals("Sexo")) {

            JOptionPane.showMessageDialog(null,
                    "Selecione uma opção");
            cmbcurso.setBackground(Color.yellow);
            cmbsexo.setBackground(Color.yellow);
        } else {


            SimpleDateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
            Date nascimento = null;
            Date data1 = null;

            try {
                nascimento = (Date) fmt.parse(ftxtnascimento.getText());
            } catch (ParseException ex) {
                ex.printStackTrace();
            }
            foto = txtmatricula.getText();

            try {

                Participante participante = new Participante(txtnome.getText().toUpperCase(),
                        txtsobrenome.getText().toUpperCase(), cmbsexo.getSelectedItem().toString().toUpperCase(),
                        nascimento, cmbcurso.getSelectedItem().toString().toUpperCase(), txtmatricula.getText().toUpperCase(),
                        txtprojeto.getText().toUpperCase(), (txtrg.getText().toUpperCase().replace(".", "").replace("-", "")), (ftxtcpf.getText().replace(".", "").replace("-", "")),
                        txtobs.getText().toUpperCase(), "C:/Arquivos de programas/Fotos/".concat(foto.concat(".jpg")), new Date(), new Usuario(login.idUsuario),
                        0);

                Endereco e = new Endereco(txtlogradouro.getText().toUpperCase(), txtnumero.getText().toUpperCase(),
                        txtbairro.getText().toUpperCase(), txtcidade.getText().toUpperCase(),
                        Integer.parseInt(ftxtcep.getText().replace(".", "").replace("-", "")),
                        txtcomplemento.getText().toUpperCase(), txtuf.getText().toUpperCase(), new Participante(txtmatricula.getText()));

                Contato cont = new Contato(ftxttel.getText().replace("(", "").replace(")", "").replace("-", "").replace("_", ""),
                        (ftxtcel.getText().replace("(", "").replace(")", "").replace("-", "").replace("_", "")),
                        txtemail.getText().toLowerCase(), new Participante(txtmatricula.getText()));
                ParticipanteDAO p = new ParticipanteDAO();

                participante.setEndereco(e);
                participante.setContato(cont);

                p.incluirParticipante(participante);
                JOptionPane.showMessageDialog(null,
                        "Cadastro incluído com sucesso.");
                txtnome.requestFocus();
                try {
                    gerente.salvarFoto();
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
                limpaCampos();

            } catch (CreateDAOException ex) {
                Logger.getLogger(CadastroAluno.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(CadastroAluno.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btncadastrarActionPerformed

    private void txtnumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumeroKeyTyped
// SÓ aceita numero
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txtnumeroKeyTyped

    private void txtufKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtufKeyTyped
        if (Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
        String conteudo = txtuf.getText();
        if (conteudo.length() >= 2) {
            evt.consume();

        }
    }//GEN-LAST:event_txtufKeyTyped

    private void ftxtcepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxtcepFocusLost
//        WebServiceCep cep = WebServiceCep.searchCep(ftxtcep.getText());
//        
//        if (cep.wasSuccessful()) {
//            
//            ftxtcep.setText(cep.getCep().toString());
//            txtlogradouro.setText(cep.getLogradouroFull().toString());
//            txtbairro.setText(cep.getBairro().toString());
//            txtcidade.setText(cep.getCidade().toString());
//            txtuf.setText(cep.getUf().toString());
//        } else {
//            
//            JOptionPane.showMessageDialog(null, "Erro n�mero  " + cep.getResulCode());
//            JOptionPane.showMessageDialog(null, "Descri��o do erro " + cep.getResultText());
//            
//        }
    }//GEN-LAST:event_ftxtcepFocusLost

    private void ftxttelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxttelFocusLost
// TODO add your handling code here:
        ftxtcel.setText(ftxttel.getText());

    }//GEN-LAST:event_ftxttelFocusLost

    private void ftxtnascimentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxtnascimentoFocusGained
        // TODO add your handling code here:
        ftxtnascimento.selectAll();
    }//GEN-LAST:event_ftxtnascimentoFocusGained

    private void ftxtnascimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxtnascimentoFocusLost
        // TODO add your handling code here:
        if (ftxtnascimento.getText().equals("  /  /    ")) {
        } else {
            Pattern p = Pattern.compile("^(?:(?:31(\\/|-|\\.)(?:0?[13578]|1[02]))\\1|(?:(?:29|30)(\\/|-|\\.)(?:0?[1,3-9]|1[0-2])\\2))(?:(?:1[6-9]|[2-9]\\d)?\\d{2})$|^(?:29(\\/|-|\\.)0?2\\3(?:(?:(?:1[6-9]|[2-9]\\d)?(?:0[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00))))$|^(?:0?[1-9]|1\\d|2[0-8])(\\/|-|\\.)(?:(?:0?[1-9])|(?:1[0-2]))\\4(?:(?:1[6-9]|[2-9]\\d)?\\d{2})$");
            Matcher m = p.matcher(ftxtnascimento.getText());
            if (!m.find()) {
                JOptionPane.showMessageDialog(null, "Data inválida.");
            }
        }
    }//GEN-LAST:event_ftxtnascimentoFocusLost

    private void cmbcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcursoActionPerformed
        if (!cmbsexo.getSelectedItem().equals("Sexo")) {
            cmbsexo.setBackground(Color.white);
        }
    }//GEN-LAST:event_cmbcursoActionPerformed

    private void txtmatriculaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmatriculaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmatriculaFocusLost

    private void cmbsexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbsexoActionPerformed
        if (!cmbsexo.getSelectedItem().equals("Sexo")) {
            cmbsexo.setBackground(Color.white);
        }
    }//GEN-LAST:event_cmbsexoActionPerformed

    private void ftxtcpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxtcpfFocusLost
        // TODO add your handling code here:
        Validacao v = new Validacao();

        if (v.calculaCPF(ftxtcpf.getText().replace(".", "").replace("-", ""))) {
        } else {

            JOptionPane.showMessageDialog(null, "CPF inválido.");

        }

    }//GEN-LAST:event_ftxtcpfFocusLost

    private void txtnomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomeKeyReleased
        txtnome.setBackground(Color.white);
    }//GEN-LAST:event_txtnomeKeyReleased

    private void txtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeActionPerformed
    }//GEN-LAST:event_txtnomeActionPerformed

    private void txtsobrenomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsobrenomeKeyReleased
        txtsobrenome.setBackground(Color.white);
    }//GEN-LAST:event_txtsobrenomeKeyReleased

    private void ftxtnascimentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxtnascimentoKeyReleased
        ftxtnascimento.setBackground(Color.white);
    }//GEN-LAST:event_ftxtnascimentoKeyReleased

    private void cmbsexoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbsexoKeyReleased
    }//GEN-LAST:event_cmbsexoKeyReleased

    private void ftxttelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxttelKeyReleased
        ftxttel.setBackground(Color.white);
    }//GEN-LAST:event_ftxttelKeyReleased

    private void txtmatriculaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmatriculaKeyReleased
        txtmatricula.setBackground(Color.white);
    }//GEN-LAST:event_txtmatriculaKeyReleased

    private void cmbcursoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbcursoKeyReleased
        cmbcurso.setBackground(Color.white);
    }//GEN-LAST:event_cmbcursoKeyReleased

    private void txtprojetoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprojetoKeyReleased
        txtprojeto.setBackground(Color.white);
    }//GEN-LAST:event_txtprojetoKeyReleased

    private void ftxtcepKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxtcepKeyReleased
        ftxtcep.setBackground(Color.white);
    }//GEN-LAST:event_ftxtcepKeyReleased

    private void txtlogradouroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlogradouroKeyReleased
        txtlogradouro.setBackground(Color.white);
    }//GEN-LAST:event_txtlogradouroKeyReleased

    private void txtnumeroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumeroKeyReleased
        txtnumero.setBackground(Color.white);
    }//GEN-LAST:event_txtnumeroKeyReleased

    private void txtbairroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbairroKeyReleased
        txtbairro.setBackground(Color.white);
    }//GEN-LAST:event_txtbairroKeyReleased

    private void txtcidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcidadeKeyReleased
        txtcidade.setBackground(Color.white);
    }//GEN-LAST:event_txtcidadeKeyReleased

    private void txtufKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtufKeyReleased
        txtuf.setBackground(Color.white);
    }//GEN-LAST:event_txtufKeyReleased

    private void jPanel2ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jPanel2ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2ComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new CadastroAluno().setVisible(true);
                } catch (SQLException ex) {
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btncadastrar;
    private java.awt.Button btnlimpar;
    private java.awt.Button btnsair;
    private javax.swing.JComboBox cmbcurso;
    private javax.swing.JComboBox cmbsexo;
    private javax.swing.JFormattedTextField ftxtcel;
    private javax.swing.JFormattedTextField ftxtcep;
    private javax.swing.JFormattedTextField ftxtcpf;
    private javax.swing.JFormattedTextField ftxtnascimento;
    private javax.swing.JFormattedTextField ftxttel;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblnome3;
    private javax.swing.JLabel lblnome5;
    private javax.swing.JTextField txtbairro;
    private javax.swing.JTextField txtcidade;
    private javax.swing.JTextField txtcomplemento;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtlogradouro;
    public static javax.swing.JFormattedTextField txtmatricula;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtnumero;
    private javax.swing.JTextField txtobs;
    private javax.swing.JTextField txtprojeto;
    private javax.swing.JTextField txtrg;
    private javax.swing.JTextField txtsobrenome;
    private javax.swing.JTextField txtuf;
    // End of variables declaration//GEN-END:variables
}
