/*
 * CadastroContato.java
 *
 * Created on 6 de Outubro de 2011, 08:51
 */
package br.com.gecel.view;

import br.com.gecel.util.Validacao;
import br.com.gecel.control.Conexao;
import br.com.gecel.dao.LoginDAO;
import br.com.gecel.dao.ParticipanteDAO;
import br.com.gecel.exception.CreateDAOException;
import br.com.gecel.model.entity.Contato;
import br.com.gecel.model.entity.Endereco;
import br.com.gecel.model.entity.Participante;
import java.awt.Color;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Familia-Silva
 */
public final class ConsultaAluno extends javax.swing.JFrame {
  //private static conexao b;

  MaskFormatter FormatoData, FormatoCpf, FormatoCnpj,
          FormatoCep, FormatoTel1, FormatoTel2;
  Login login;
  Conexao connect;
  LoginDAO loginDAO;
  ParticipanteDAO participanteDAO;
  String foto;
  String sexo;
  Integer idParcipamente;

  /**
   * Creates new form CadastroContato
   */
  public ConsultaAluno() throws SQLException {
    initComponents();
    connect = new Conexao();
    id.setVisible(false);
    apresentaDados();

  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtsobrenome = new javax.swing.JTextField();
        try
        {
            FormatoTel1 = new MaskFormatter("(##)####-####");
        }
        catch (Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possível gerar máscara, erro = " +erro);
        }

        ftxttel = new JFormattedTextField (FormatoTel1);
        try
        {
            FormatoTel1 = new MaskFormatter("(##)####-####");
        }
        catch (Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possível gerar máscara, erro = " +erro);
        }

        ftxtcel = new JFormattedTextField (FormatoTel1);
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbcurso = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        try
        {
            FormatoCep = new MaskFormatter("##.###-###");
        }
        catch (Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possível gerar máscara, erro = " +erro);
        }

        ftxtcep = new JFormattedTextField (FormatoCep);
        txtlogradouro = new javax.swing.JTextField();
        txtbairro = new javax.swing.JTextField();
        txtcomplemento = new javax.swing.JTextField();
        txtcidade = new javax.swing.JTextField();
        txtuf = new javax.swing.JTextField();
        txtnumero = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnalterar = new java.awt.Button();
        btnlimpar = new java.awt.Button();
        jPanel2 = new javax.swing.JPanel();
        lblimagem = new javax.swing.JLabel();
        btnsair = new java.awt.Button();
        txtnome = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        try
        {
            FormatoData = new MaskFormatter("##/##/####");
        }
        catch (Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possível gerar máscara, erro = " +erro);
        }

        ftxtnascimento = new JFormattedTextField (FormatoData);
        jLabel16 = new javax.swing.JLabel();

        txtmatricula = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtprojeto = new javax.swing.JTextField();
        txtrg = new javax.swing.JTextField();
        lblnome3 = new javax.swing.JLabel();
        try
        {
            FormatoCpf = new MaskFormatter("###.###.###-##");
        }
        catch (Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possível gerar máscara, erro = " +erro);
        }

        ftxtcpf = new JFormattedTextField (FormatoCpf);
        lblnome5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtobs = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        cmbsexo = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dados = new javax.swing.JTable();
        btnpesquisar = new java.awt.Button();
        cmbpesquisa = new javax.swing.JComboBox();
        txtNomeConsulta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Contato");
        setIconImages(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));
        jPanel1.setLayout(null);

        jLabel2.setText("Sobrenome");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 87, 70, 14);

        txtsobrenome.setEditable(false);
        txtsobrenome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtsobrenomeFocusGained(evt);
            }
        });
        txtsobrenome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsobrenomeKeyReleased(evt);
            }
        });
        jPanel1.add(txtsobrenome);
        txtsobrenome.setBounds(110, 80, 240, 20);

        ftxttel.setEditable(false);
        ftxttel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ftxttelKeyReleased(evt);
            }
        });
        jPanel1.add(ftxttel);
        ftxttel.setBounds(110, 160, 100, 20);

        ftxtcel.setEditable(false);
        ftxtcel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ftxtcelFocusGained(evt);
            }
        });
        jPanel1.add(ftxtcel);
        ftxtcel.setBounds(251, 160, 100, 20);

        jLabel4.setText("Tel.");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 167, 34, 14);

        jLabel5.setText("Email");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 326, 50, 14);

        cmbcurso.setEditable(false);
        cmbcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcursoActionPerformed(evt);
            }
        });
        cmbcurso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbcursoFocusGained(evt);
            }
        });
        jPanel1.add(cmbcurso);
        cmbcurso.setBounds(210, 200, 140, 20);

        jLabel7.setText("C.E.P");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 365, 34, 14);

        ftxtcep.setEditable(false);
        ftxtcep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ftxtcepFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftxtcepFocusLost(evt);
            }
        });
        ftxtcep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ftxtcepKeyReleased(evt);
            }
        });
        jPanel1.add(ftxtcep);
        ftxtcep.setBounds(110, 360, 100, 20);

        txtlogradouro.setEditable(false);
        txtlogradouro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtlogradouroFocusGained(evt);
            }
        });
        txtlogradouro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtlogradouroKeyReleased(evt);
            }
        });
        jPanel1.add(txtlogradouro);
        txtlogradouro.setBounds(300, 360, 320, 20);

        txtbairro.setEditable(false);
        txtbairro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtbairroFocusGained(evt);
            }
        });
        txtbairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbairroKeyReleased(evt);
            }
        });
        jPanel1.add(txtbairro);
        txtbairro.setBounds(290, 400, 150, 20);

        txtcomplemento.setEditable(false);
        txtcomplemento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcomplementoFocusGained(evt);
            }
        });
        jPanel1.add(txtcomplemento);
        txtcomplemento.setBounds(110, 400, 130, 20);

        txtcidade.setEditable(false);
        txtcidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcidadeFocusGained(evt);
            }
        });
        txtcidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcidadeKeyReleased(evt);
            }
        });
        jPanel1.add(txtcidade);
        txtcidade.setBounds(500, 400, 190, 20);

        txtuf.setEditable(false);
        txtuf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtufFocusGained(evt);
            }
        });
        txtuf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtufKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtufKeyTyped(evt);
            }
        });
        jPanel1.add(txtuf);
        txtuf.setBounds(720, 400, 30, 20);

        txtnumero.setEditable(false);
        txtnumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnumeroFocusGained(evt);
            }
        });
        txtnumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnumeroKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnumeroKeyTyped(evt);
            }
        });
        jPanel1.add(txtnumero);
        txtnumero.setBounds(660, 360, 90, 20);

        jLabel8.setText("Logradouro");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(225, 365, 70, 14);

        jLabel9.setText("Nº");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(632, 365, 30, 14);

        jLabel10.setText("Complemento");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 405, 80, 14);

        jLabel11.setText("Bairro");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(250, 405, 50, 14);

        jLabel12.setText("Cidade");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(450, 405, 50, 14);

        jLabel13.setText("UF");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(700, 405, 30, 14);

        jLabel14.setText("Sexo");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(218, 127, 34, 14);

        btnalterar.setEnabled(false);
        btnalterar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnalterar.setLabel("Alterar");
        btnalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnalterarActionPerformed(evt);
            }
        });
        jPanel1.add(btnalterar);
        btnalterar.setBounds(20, 430, 80, 30);

        btnlimpar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnlimpar.setLabel("Limpar");
        btnlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimparActionPerformed(evt);
            }
        });
        jPanel1.add(btnlimpar);
        btnlimpar.setBounds(130, 430, 80, 30);

        jPanel2.setLayout(null);

        lblimagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblimagem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lblimagem);
        lblimagem.setBounds(0, 0, 390, 270);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(360, 30, 390, 270);

        btnsair.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnsair.setLabel("Sair");
        btnsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsairActionPerformed(evt);
            }
        });
        jPanel1.add(btnsair);
        btnsair.setBounds(240, 430, 80, 30);

        txtnome.setEditable(false);
        txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeActionPerformed(evt);
            }
        });
        txtnome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnomeFocusGained(evt);
            }
        });
        txtnome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnomeKeyReleased(evt);
            }
        });
        jPanel1.add(txtnome);
        txtnome.setBounds(110, 40, 240, 20);

        jLabel15.setText("Nome");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(20, 50, 34, 14);

        ftxtnascimento.setEditable(false);
        ftxtnascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ftxtnascimentoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftxtnascimentoFocusLost(evt);
            }
        });
        jPanel1.add(ftxtnascimento);
        ftxtnascimento.setBounds(110, 120, 90, 20);

        jLabel16.setText("Nasc.");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(20, 127, 34, 14);

        txtmatricula.setEditable(false);
        txtmatricula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtmatriculaFocusLost(evt);
            }
        });
        txtmatricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmatriculaKeyReleased(evt);
            }
        });
        jPanel1.add(txtmatricula);
        txtmatricula.setBounds(110, 200, 50, 20);

        jLabel17.setText("Matrícula");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(20, 208, 60, 14);

        jLabel18.setText("Projeto");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(20, 250, 50, 14);

        txtprojeto.setEditable(false);
        txtprojeto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtprojetoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtprojetoFocusLost(evt);
            }
        });
        txtprojeto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtprojetoKeyReleased(evt);
            }
        });
        jPanel1.add(txtprojeto);
        txtprojeto.setBounds(110, 240, 240, 20);

        txtrg.setEditable(false);
        txtrg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtrgFocusGained(evt);
            }
        });
        jPanel1.add(txtrg);
        txtrg.setBounds(110, 280, 90, 20);

        lblnome3.setText("RG");
        jPanel1.add(lblnome3);
        lblnome3.setBounds(20, 286, 60, 14);

        ftxtcpf.setEditable(false);
        ftxtcpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ftxtcpfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftxtcpfFocusLost(evt);
            }
        });
        jPanel1.add(ftxtcpf);
        ftxtcpf.setBounds(250, 280, 100, 20);

        lblnome5.setText("CPF");
        jPanel1.add(lblnome5);
        lblnome5.setBounds(218, 286, 40, 14);

        jLabel6.setText("Observação");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(372, 326, 90, 14);

        txtobs.setEditable(false);
        txtobs.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtobsFocusGained(evt);
            }
        });
        jPanel1.add(txtobs);
        txtobs.setBounds(450, 320, 300, 20);

        txtemail.setEditable(false);
        txtemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtemailFocusGained(evt);
            }
        });
        jPanel1.add(txtemail);
        txtemail.setBounds(110, 320, 240, 20);

        jLabel19.setText("Curso");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(170, 206, 34, 14);

        cmbsexo.setEditable(false);
        cmbsexo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbsexoFocusGained(evt);
            }
        });
        jPanel1.add(cmbsexo);
        cmbsexo.setBounds(250, 120, 100, 20);

        jLabel20.setText("Cel.");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(223, 167, 34, 14);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 762, 470);

        id.setText("jLabel1");
        getContentPane().add(id);
        id.setBounds(130, 30, 90, 14);

        dados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matrícula", "Nome", "Curso", "Email", "Projeto", "Criador", "Cadastro "
            }
        ));
        dados.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        dados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dados);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 520, 760, 160);

        btnpesquisar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnpesquisar.setLabel("Pesquisar");
        btnpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btnpesquisar);
        btnpesquisar.setBounds(310, 482, 90, 30);

        cmbpesquisa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione a consulta", "Nome", "Matrícula", "Todos" }));
        cmbpesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbpesquisaActionPerformed(evt);
            }
        });
        getContentPane().add(cmbpesquisa);
        cmbpesquisa.setBounds(10, 492, 150, 22);

        txtNomeConsulta.setEnabled(false);
        getContentPane().add(txtNomeConsulta);
        txtNomeConsulta.setBounds(170, 492, 130, 20);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-789)/2, (screenSize.height-719)/2, 789, 719);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//// coloca uma figura na barra de título da janela  
//URL url = this.getClass().getResource("/br/com/gecel/imagem/ana.jpg");  
//Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);  
//this.setIconImage(imagemTitulo);  
      //        try {
//// TODO add your handling code here:
//            txtcodigo.setText(String.valueOf(b.queryCodiContato()));
//        } catch (SQLException ex) {
//            ex.printStackTrace();
//        }
      //this.setExtendedState(this.MAXIMIZED_BOTH);
      // this.setUndecorated(true);  
      //this.getRootPane().setWindowDecorationStyle(JRootPane.FRAME); 
    }//GEN-LAST:event_formWindowOpened

    private void btnsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsairActionPerformed
      limpaCampos();
      dispose();
    }//GEN-LAST:event_btnsairActionPerformed

    private void btnlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimparActionPerformed

      limpaCampos();

    }//GEN-LAST:event_btnlimparActionPerformed
  public void limpaCampos() {
    lblimagem.setIcon(new ImageIcon(""));
    txtnome.setBackground(Color.white);
    txtsobrenome.setBackground(Color.white);
    ftxttel.setBackground(Color.white);
    ftxtcel.setBackground(Color.white);
    ftxtcep.setBackground(Color.white);
    ftxtcpf.setBackground(Color.white);
    txtbairro.setBackground(Color.white);
    txtlogradouro.setBackground(Color.white);
    txtcidade.setBackground(Color.white);
    txtemail.setBackground(Color.white);
    txtrg.setBackground(Color.white);
    txtcomplemento.setBackground(Color.white);
    txtuf.setBackground(Color.white);
    txtnumero.setBackground(Color.white);
    txtprojeto.setBackground(Color.white);
    txtobs.setBackground(Color.white);
    txtmatricula.setBackground(Color.white);
    ftxtnascimento.setBackground(Color.white);
    cmbsexo.setBackground(Color.white);
    cmbcurso.setBackground(Color.white);

    cmbcurso.setEditable(false);
    txtobs.setEditable(false);
    txtprojeto.setEditable(false);
    ftxtnascimento.setEditable(false);
    txtsobrenome.setEditable(false);
    ftxttel.setEditable(false);
    ftxtcel.setEditable(false);
    ftxtcep.setEditable(false);
    txtbairro.setEditable(false);
    txtlogradouro.setEditable(false);
    txtcidade.setEditable(false);
    txtuf.setEditable(false);
    txtnumero.setEditable(false);
    txtnome.setEditable(false);
    txtcomplemento.setEditable(false);
    txtrg.setEditable(false);
    txtemail.setEditable(false);
    txtnome.requestFocus();
    cmbcurso.setEditable(false);
    cmbsexo.setEditable(false);
    ftxtcpf.setEditable(false);

    txtmatricula.setText("");
    cmbcurso.setText("");
    txtobs.setText("");
    txtprojeto.setText("");
    ftxtnascimento.setText("");
    txtsobrenome.setText("");
    ftxttel.setText("");
    ftxtcel.setText("");
    ftxtcep.setText("");
    txtbairro.setText("");
    txtlogradouro.setText("");
    txtcidade.setText("");
    txtuf.setText("");
    txtnumero.setText("");
    txtnome.setText("");
    txtcomplemento.setText("");
    txtrg.setText("");
    txtemail.setText("");
    txtnome.requestFocus();
    cmbcurso.setText("");
    cmbsexo.setText("");
    ftxtcpf.setValue("");
    txtNomeConsulta.setText("");
    txtNomeConsulta.setEnabled(false);
    cmbpesquisa.setSelectedIndex(0);
    btnalterar.setEnabled(false);
    ((DefaultTableModel) dados.getModel()).setNumRows(0);
  }
    private void btnalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalterarActionPerformed
// TODO add your handling code here:
//      numeroRegistros = Integer.parseInt(id.getText());

      if (txtsobrenome.getText().equals("")
              || ftxtnascimento.getText().equals("")
              || txtnome.getText().equals("")
              || ftxttel.getText().equals("")
              || ftxtcep.getText().equals("")
              || txtbairro.getText().equals("")
              || txtlogradouro.getText().equals("")
              || txtprojeto.getText().equals("")
              || txtmatricula.getText().equals("")
              || txtcidade.getText().equals("")
              || txtuf.getText().equals("")
              || txtnumero.getText().equals("")) {

        JOptionPane.showMessageDialog(null,
                "Campo obrigatário");
        ftxtnascimento.setBackground(Color.yellow);
        txtnome.setBackground(Color.yellow);
        txtprojeto.setBackground(Color.yellow);
        txtmatricula.setBackground(Color.yellow);
        txtsobrenome.setBackground(Color.yellow);
        ftxttel.setBackground(Color.yellow);
        ftxtcep.setBackground(Color.yellow);
        txtbairro.setBackground(Color.yellow);
        txtlogradouro.setBackground(Color.yellow);
        txtcidade.setBackground(Color.yellow);
        txtuf.setBackground(Color.yellow);
        txtnumero.setBackground(Color.yellow);
      } else {

        try {

          SimpleDateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
          Date nascimento = null;

          try {
            nascimento = (Date) fmt.parse(ftxtnascimento.getText());
          } catch (ParseException ex) {
          }
          Participante participante = new Participante(txtnome.getText().toUpperCase(),
                  txtsobrenome.getText().toUpperCase(),
                  cmbsexo.getText().toUpperCase(),
                  nascimento,
                  cmbcurso.getText().toUpperCase(),
                  txtprojeto.getText().toUpperCase(),
                  txtrg.getText().toUpperCase().replace(".", "").replace("-", ""),
                  ftxtcpf.getText().replace(".", "").replace("-", ""),
                  txtobs.getText().toUpperCase(),
                  new Date());

          Contato contato = new Contato(ftxttel.getText().replace("(", "").replace(")", "").replace("-", "").replace("_", ""),
                  (ftxtcel.getText().replace("(", "").replace(")", "").replace("-", "").replace("_", "")),
                  txtemail.getText().toLowerCase(), new Participante(txtmatricula.getText()));

          Endereco endereco = new Endereco(txtlogradouro.getText().toUpperCase(), txtnumero.getText().toUpperCase(),
                  txtbairro.getText().toUpperCase(), txtcidade.getText().toUpperCase(),
                  Integer.parseInt(ftxtcep.getText().replace(".", "").replace("-", "")),
                  txtcomplemento.getText().toUpperCase(), txtuf.getText().toUpperCase(), new Participante(txtmatricula.getText()));

          participante.setMatricula(txtmatricula.getText());

          participante.setContato(contato);
          participante.setEndereco(endereco);

          participanteDAO.updateParticipante(participante);

          JOptionPane.showMessageDialog(null,
                  "Cadastro alterado com sucesso.");
          txtnome.requestFocus();

          limpaCampos();

        } catch (SQLException ex) {
          Logger.getLogger(ConsultaAluno.class.getName()).log(Level.SEVERE, null, ex);
        } catch (CreateDAOException ex) {
          Logger.getLogger(ConsultaAluno.class.getName()).log(Level.SEVERE, null, ex);
        }

      }

    }//GEN-LAST:event_btnalterarActionPerformed

    private void txtnumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumeroKeyTyped
// SÓ aceita numero
      if (!Character.isDigit(evt.getKeyChar())) {
        evt.consume();
      }
    }//GEN-LAST:event_txtnumeroKeyTyped

    private void txtufKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtufKeyTyped
      if (Character.isDigit(evt.getKeyChar())) {
        evt.consume();
      }
      String conteudo = txtuf.getText();
      if (conteudo.length() >= 2) {
        evt.consume();

      }
    }//GEN-LAST:event_txtufKeyTyped

    private void ftxtcepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxtcepFocusLost
//        WebServiceCep cep = WebServiceCep.searchCep(ftxtcep.getText());
//        
//        if (cep.wasSuccessful()) {
//            
//            ftxtcep.setText(cep.getCep().toString());
//            txtlogradouro.setText(cep.getLogradouroFull().toString());
//            txtbairro.setText(cep.getBairro().toString());
//            txtcidade.setText(cep.getCidade().toString());
//            txtuf.setText(cep.getUf().toString());
//        } else {
//            
//            JOptionPane.showMessageDialog(null, "Erro n�mero  " + cep.getResulCode());
//            JOptionPane.showMessageDialog(null, "Descri��o do erro " + cep.getResultText());
//            
//        }
    }//GEN-LAST:event_ftxtcepFocusLost
  public void apresentaDados() {

    final DefaultTableModel modelo = (DefaultTableModel) dados.getModel();
    dados.getColumnModel().getColumn(0).setPreferredWidth(55);
    dados.getColumnModel().getColumn(1).setPreferredWidth(210);
    dados.getColumnModel().getColumn(2).setPreferredWidth(150);
    dados.getColumnModel().getColumn(3).setPreferredWidth(150);
    dados.getColumnModel().getColumn(4).setPreferredWidth(150);
    dados.getColumnModel().getColumn(5).setPreferredWidth(150);
    dados.getColumnModel().getColumn(6).setPreferredWidth(85);

    modelo.setNumRows(0);
  }
    private void ftxtnascimentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxtnascimentoFocusGained
      ftxtnascimento.selectAll();
    }//GEN-LAST:event_ftxtnascimentoFocusGained

    private void ftxtnascimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxtnascimentoFocusLost
      // TODO add your handling code here:
      if (ftxtnascimento.getText().equals("  /  /    ")) {
      } else {
        Pattern p = Pattern.compile("^(?:(?:31(\\/|-|\\.)(?:0?[13578]|1[02]))\\1|(?:(?:29|30)(\\/|-|\\.)(?:0?[1,3-9]|1[0-2])\\2))(?:(?:1[6-9]|[2-9]\\d)?\\d{2})$|^(?:29(\\/|-|\\.)0?2\\3(?:(?:(?:1[6-9]|[2-9]\\d)?(?:0[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00))))$|^(?:0?[1-9]|1\\d|2[0-8])(\\/|-|\\.)(?:(?:0?[1-9])|(?:1[0-2]))\\4(?:(?:1[6-9]|[2-9]\\d)?\\d{2})$");
        Matcher m = p.matcher(ftxtnascimento.getText());
        if (!m.find()) {
          JOptionPane.showMessageDialog(null, "Data inválida.");
        }
      }
    }//GEN-LAST:event_ftxtnascimentoFocusLost

    private void txtmatriculaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmatriculaFocusLost
      // TODO add your handling code here:
    }//GEN-LAST:event_txtmatriculaFocusLost

    private void ftxtcpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxtcpfFocusLost
      // TODO add your handling code here:
      Validacao v = new Validacao();

      if (v.calculaCPF(ftxtcpf.getText().replace(".", "").replace("-", ""))) {
      } else {

        JOptionPane.showMessageDialog(null, "CPF inválido.");

      }

    }//GEN-LAST:event_ftxtcpfFocusLost

    private void txtnomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomeKeyReleased
      txtnome.setBackground(Color.white);
    }//GEN-LAST:event_txtnomeKeyReleased

    private void txtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeActionPerformed
    }//GEN-LAST:event_txtnomeActionPerformed

    private void txtsobrenomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsobrenomeKeyReleased
      txtsobrenome.setBackground(Color.white);
    }//GEN-LAST:event_txtsobrenomeKeyReleased

    private void ftxttelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxttelKeyReleased
      ftxttel.setBackground(Color.white);
    }//GEN-LAST:event_ftxttelKeyReleased

    private void txtmatriculaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmatriculaKeyReleased
      txtmatricula.setBackground(Color.white);
    }//GEN-LAST:event_txtmatriculaKeyReleased

    private void txtprojetoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprojetoKeyReleased
      txtprojeto.setBackground(Color.white);
    }//GEN-LAST:event_txtprojetoKeyReleased

    private void ftxtcepKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxtcepKeyReleased
      ftxtcep.setBackground(Color.white);
    }//GEN-LAST:event_ftxtcepKeyReleased

    private void txtlogradouroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlogradouroKeyReleased
      txtlogradouro.setBackground(Color.white);
    }//GEN-LAST:event_txtlogradouroKeyReleased

    private void txtnumeroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumeroKeyReleased
      txtnumero.setBackground(Color.white);
    }//GEN-LAST:event_txtnumeroKeyReleased

    private void txtbairroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbairroKeyReleased
      txtbairro.setBackground(Color.white);
    }//GEN-LAST:event_txtbairroKeyReleased

    private void txtcidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcidadeKeyReleased
      txtcidade.setBackground(Color.white);
    }//GEN-LAST:event_txtcidadeKeyReleased

    private void txtufKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtufKeyReleased
      txtuf.setBackground(Color.white);
    }//GEN-LAST:event_txtufKeyReleased

    private void btnpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesquisarActionPerformed
      // TODO add your handling code here:
      final DefaultTableModel modelo = (DefaultTableModel) dados.getModel();
      SimpleDateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
      participanteDAO = new ParticipanteDAO();

      if (cmbpesquisa.getSelectedItem().equals("Selecione a consulta")) {

        JOptionPane.showMessageDialog(null, "Selecione tipo de consulta.");
        cmbpesquisa.requestFocus();

      } else if (cmbpesquisa.getSelectedItem().equals("Todos")) {
        try {
          ((DefaultTableModel) dados.getModel()).setNumRows(0);
          ArrayList<Participante> participantes = participanteDAO.consultaParticipante(txtNomeConsulta.getText(), 1000);

          for (Participante participante : participantes) {

            modelo.addRow(new Object[]{participante.getMatricula(), participante.getNome(),
                      participante.getCurso(), participante.getContato().getEmail(),
                      participante.getProjeto(), participante.getCriador().getNome(),
                      new SimpleDateFormat("dd/MM/yyyy").format(participante.getCadastro())});

          }
        } catch (SQLException ex) {
          Logger.getLogger(ConsultaAluno.class.getName()).log(Level.SEVERE, null, ex);
        } catch (CreateDAOException ex) {
          Logger.getLogger(ConsultaAluno.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NullPointerException ex) {
          JOptionPane.showMessageDialog(null, "Participante não encontrado.");
        }
      } else if (cmbpesquisa.getSelectedItem().equals("Matrícula")) {
        if ((txtNomeConsulta.getText().equals("") && (!cmbpesquisa.getSelectedItem().equals("Todos")))) {
          JOptionPane.showMessageDialog(null, "Digite a matrícula.");
          txtNomeConsulta.requestFocus();
        } else {
          try {
            ((DefaultTableModel) dados.getModel()).setNumRows(0);
            ArrayList<Participante> participantes = participanteDAO.consultaParticipante(txtNomeConsulta.getText(), 1);

            for (Participante participante : participantes) {

              modelo.addRow(new Object[]{participante.getMatricula(), participante.getNome(),
                        participante.getCurso(), participante.getContato().getEmail(),
                        participante.getProjeto(), participante.getCriador().getNome(),
                        new SimpleDateFormat("dd/MM/yyyy").format(participante.getCadastro())});

            }
          } catch (SQLException ex) {
            Logger.getLogger(ConsultaAluno.class.getName()).log(Level.SEVERE, null, ex);
          } catch (CreateDAOException ex) {
            Logger.getLogger(ConsultaAluno.class.getName()).log(Level.SEVERE, null, ex);
          } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Participante não encontrado.");
          }
          System.out.println("Matícula");
        }
      } else if (cmbpesquisa.getSelectedItem().equals("Nome")) {
        if ((txtNomeConsulta.getText().equals("") && (!cmbpesquisa.getSelectedItem().equals("Todos")))) {
          JOptionPane.showMessageDialog(null, "Digite o nome.");
          txtNomeConsulta.requestFocus();
        } else {
          try {

            ((DefaultTableModel) dados.getModel()).setNumRows(0);
            ArrayList<Participante> participantes = participanteDAO.consultaParticipante(txtNomeConsulta.getText().trim(), 2);

            for (Participante participante : participantes) {

              modelo.addRow(new Object[]{participante.getMatricula(), participante.getNome(),
                        participante.getCurso(), participante.getContato().getEmail(),
                        participante.getProjeto(), participante.getCriador().getNome(),
                        new SimpleDateFormat("dd/MM/yyyy").format(participante.getCadastro())});

            }

          } catch (SQLException ex) {
            Logger.getLogger(ConsultaAluno.class.getName()).log(Level.SEVERE, null, ex);
          } catch (CreateDAOException ex) {
            Logger.getLogger(ConsultaAluno.class.getName()).log(Level.SEVERE, null, ex);
          } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Participante não encontrado.");
          }
          System.out.println("Nome");
        }
      }
    }//GEN-LAST:event_btnpesquisarActionPerformed

  private void dadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dadosMouseClicked
    try {
      habilitaCampos();
      ArrayList<Participante> participante = participanteDAO.consultaParticipante(dados.getValueAt(dados.getSelectedRow(), 0).toString(), 1);

      txtnome.setText(participante.get(0).getNome());
      txtsobrenome.setText(participante.get(0).getSobreNome());
      ftxtnascimento.setText(new SimpleDateFormat("dd/MM/yyyy").format(participante.get(0).getNascimento()));
      cmbsexo.setText((participante.get(0).getSexo()));
      ftxttel.setText(participante.get(0).getContato().getTelefoneFixo());
      ftxtcel.setText(participante.get(0).getContato().getCelular());
      txtmatricula.setText(participante.get(0).getMatricula());
      cmbcurso.setText(participante.get(0).getCurso());
      txtprojeto.setText(participante.get(0).getProjeto());
      txtrg.setText(participante.get(0).getRg());
      ftxtcpf.setText(participante.get(0).getCpf());
      txtemail.setText(participante.get(0).getContato().getEmail());
      txtobs.setText(participante.get(0).getObservacao());
      ftxtcep.setText(String.valueOf(participante.get(0).getEndereco().getCep()));
      txtlogradouro.setText(participante.get(0).getEndereco().getLogradouro());
      txtnumero.setText(participante.get(0).getEndereco().getNumero());
      txtcomplemento.setText(participante.get(0).getEndereco().getComplemento());
      txtbairro.setText(participante.get(0).getEndereco().getBairro());
      txtcidade.setText(participante.get(0).getEndereco().getCidade());
      txtuf.setText(participante.get(0).getEndereco().getUf());
      System.out.println(participante.get(0).getEndereco().getUf());
      lblimagem.setIcon(new ImageIcon(participante.get(0).getFoto()));
    } catch (SQLException ex) {
      Logger.getLogger(ConsultaAluno.class.getName()).log(Level.SEVERE, null, ex);
    } catch (CreateDAOException ex) {
      Logger.getLogger(ConsultaAluno.class.getName()).log(Level.SEVERE, null, ex);
    }

  }//GEN-LAST:event_dadosMouseClicked
  public void habilitaCampos() {
    txtnome.setBackground(Color.white);
    txtsobrenome.setBackground(Color.white);
    ftxttel.setBackground(Color.white);
    ftxtcep.setBackground(Color.white);
    txtbairro.setBackground(Color.white);
    txtlogradouro.setBackground(Color.white);
    txtcidade.setBackground(Color.white);
    txtuf.setBackground(Color.white);
    txtnumero.setBackground(Color.white);
    txtprojeto.setBackground(Color.white);
    txtobs.setBackground(Color.white);
    txtmatricula.setBackground(Color.white);
    ftxtnascimento.setBackground(Color.white);
    cmbsexo.setBackground(Color.white);
    cmbcurso.setBackground(Color.white);

    cmbcurso.setEditable(true);
    txtobs.setEditable(true);
    txtprojeto.setEditable(true);
    ftxtnascimento.setEditable(true);
    txtsobrenome.setEditable(true);
    ftxttel.setEditable(true);
    ftxtcel.setEditable(true);
    ftxtcep.setEditable(true);
    txtbairro.setEditable(true);
    txtlogradouro.setEditable(true);
    txtcidade.setEditable(true);
    txtuf.setEditable(true);
    txtnumero.setEditable(true);
    txtnome.setEditable(true);
    txtcomplemento.setEditable(true);
    txtrg.setEditable(true);
    txtemail.setEditable(true);
    txtnome.requestFocus();
    cmbcurso.setEditable(true);
    cmbsexo.setEditable(true);
    ftxtcpf.setEditable(true);
    txtNomeConsulta.setEditable(true);
    btnalterar.setEnabled(true);
  }
  private void cmbcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcursoActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_cmbcursoActionPerformed

  private void cmbpesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbpesquisaActionPerformed
    // TODO add your handling code here:
    if (cmbpesquisa.getSelectedItem().equals("Selecione a consulta")) {
      txtNomeConsulta.setEnabled(false);
      txtNomeConsulta.setText("");
    } else if (cmbpesquisa.getSelectedItem().equals("Todos")) {
      txtNomeConsulta.setEnabled(false);
      txtNomeConsulta.setText("");
    } else if (cmbpesquisa.getSelectedItem().equals("Nome")) {
      txtNomeConsulta.setEnabled(true);
      txtNomeConsulta.requestFocus();
      txtNomeConsulta.setText("");
    } else if (cmbpesquisa.getSelectedItem().equals("Matrícula")) {
      txtNomeConsulta.setEnabled(true);
      txtNomeConsulta.requestFocus();
      txtNomeConsulta.setText("");
    }
  }//GEN-LAST:event_cmbpesquisaActionPerformed

  private void txtnomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnomeFocusGained
    txtnome.selectAll();
  }//GEN-LAST:event_txtnomeFocusGained

  private void txtsobrenomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsobrenomeFocusGained

    txtsobrenome.selectAll();

  }//GEN-LAST:event_txtsobrenomeFocusGained

  private void cmbsexoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbsexoFocusGained
    cmbsexo.selectAll();
  }//GEN-LAST:event_cmbsexoFocusGained

  private void ftxtcelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxtcelFocusGained
    ftxtcel.selectAll();
  }//GEN-LAST:event_ftxtcelFocusGained

  private void cmbcursoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbcursoFocusGained
    cmbcurso.selectAll();
  }//GEN-LAST:event_cmbcursoFocusGained

  private void txtprojetoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtprojetoFocusLost
    txtprojeto.selectAll();
  }//GEN-LAST:event_txtprojetoFocusLost

  private void txtrgFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtrgFocusGained
    txtrg.selectAll();
  }//GEN-LAST:event_txtrgFocusGained

  private void ftxtcpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxtcpfFocusGained
    ftxtcpf.selectAll();
  }//GEN-LAST:event_ftxtcpfFocusGained

  private void txtemailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtemailFocusGained
    txtemail.selectAll();
  }//GEN-LAST:event_txtemailFocusGained

  private void txtobsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtobsFocusGained
    txtobs.selectAll();
  }//GEN-LAST:event_txtobsFocusGained

  private void ftxtcepFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxtcepFocusGained
    ftxtcep.selectAll();
  }//GEN-LAST:event_ftxtcepFocusGained

  private void txtlogradouroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtlogradouroFocusGained
    txtlogradouro.selectAll();
  }//GEN-LAST:event_txtlogradouroFocusGained

  private void txtnumeroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnumeroFocusGained
    txtnumero.selectAll();
  }//GEN-LAST:event_txtnumeroFocusGained

  private void txtcomplementoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcomplementoFocusGained
    txtcomplemento.selectAll();
  }//GEN-LAST:event_txtcomplementoFocusGained

  private void txtbairroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtbairroFocusGained
    txtbairro.selectAll();
  }//GEN-LAST:event_txtbairroFocusGained

  private void txtcidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcidadeFocusGained
    txtcidade.selectAll();
  }//GEN-LAST:event_txtcidadeFocusGained

  private void txtufFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtufFocusGained
    txtuf.selectAll();

  }//GEN-LAST:event_txtufFocusGained

  private void txtprojetoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtprojetoFocusGained
    txtprojeto.selectAll();

  }//GEN-LAST:event_txtprojetoFocusGained

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {

      @Override
      public void run() {
        try {
          new ConsultaAluno().setVisible(true);
        } catch (SQLException ex) {
        }
      }
    });
  }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnalterar;
    private java.awt.Button btnlimpar;
    private java.awt.Button btnpesquisar;
    private java.awt.Button btnsair;
    private javax.swing.JTextField cmbcurso;
    private javax.swing.JComboBox cmbpesquisa;
    private javax.swing.JTextField cmbsexo;
    private javax.swing.JTable dados;
    private javax.swing.JFormattedTextField ftxtcel;
    private javax.swing.JFormattedTextField ftxtcep;
    private javax.swing.JFormattedTextField ftxtcpf;
    private javax.swing.JFormattedTextField ftxtnascimento;
    private javax.swing.JFormattedTextField ftxttel;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblimagem;
    private javax.swing.JLabel lblnome3;
    private javax.swing.JLabel lblnome5;
    private javax.swing.JTextField txtNomeConsulta;
    private javax.swing.JTextField txtbairro;
    private javax.swing.JTextField txtcidade;
    private javax.swing.JTextField txtcomplemento;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtlogradouro;
    private javax.swing.JFormattedTextField txtmatricula;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtnumero;
    private javax.swing.JTextField txtobs;
    private javax.swing.JTextField txtprojeto;
    private javax.swing.JTextField txtrg;
    private javax.swing.JTextField txtsobrenome;
    private javax.swing.JTextField txtuf;
    // End of variables declaration//GEN-END:variables
}
