/*
 * Login.java
 *
 * Created on 14 de Setembro de 2011, 14:27
 */
package br.com.gecel.view;

import br.com.gecel.control.Conexao;
import br.com.gecel.dao.LoginDAO;
import br.com.gecel.exception.CreateDAOException;
import br.com.gecel.model.entity.Usuario;
import java.awt.AWTKeyStroke;
import java.awt.KeyboardFocusManager;
import java.awt.Label;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Familia-Silva
 */
public class Login extends javax.swing.JFrame {

    private Conexao connect;
    private int conta = -1;
    public String imagens = null;
    public static int idUsuario;
    public static JLabel imagem;

    /**
     * Creates new form Login
     */
    public Login() throws SQLException {
        initComponents();
        btnconsulta1.setVisible(true);
        btnconsulta.setVisible(true);
        txtsenha.setVisible(true);
        connect = new Conexao();
        connect.beginTransection();
        txtsenha.setText("");
        txtsenha.setVisible(true);
        enter();
        setResizable(false);

    }

    public void enter() {
// Enter simula tecla Tab
        HashSet conj = new HashSet(getFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS));
        conj.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_ENTER, 0));
        setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, conj);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtusuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtsenha = new javax.swing.JPasswordField();
        btnconsulta = new java.awt.Button();
        btnconsulta1 = new java.awt.Button();
        lblimagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtusuario);
        txtusuario.setBounds(60, 10, 190, 20);

        jLabel1.setText("Usuário");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 60, 14);

        jLabel2.setText("Senha");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 40, 60, 14);
        getContentPane().add(txtsenha);
        txtsenha.setBounds(60, 40, 190, 20);

        btnconsulta.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnconsulta.setLabel("Acessar");
        btnconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultaActionPerformed(evt);
            }
        });
        getContentPane().add(btnconsulta);
        btnconsulta.setBounds(270, 10, 80, 20);

        btnconsulta1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnconsulta1.setLabel("Sair");
        btnconsulta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsulta1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnconsulta1);
        btnconsulta1.setBounds(270, 40, 80, 20);

        lblimagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gecel/imagem/logo.JPG"))); // NOI18N
        getContentPane().add(lblimagem);
        lblimagem.setBounds(0, 0, 390, 250);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-394)/2, (screenSize.height-280)/2, 394, 280);
    }// </editor-fold>//GEN-END:initComponents

    private void btnconsulta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsulta1ActionPerformed
// TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnconsulta1ActionPerformed

    private void btnconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultaActionPerformed

        if (txtusuario.getText().equals("") || txtsenha.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Usuário ou Senha inválida.");
        } else {
            if (conta <= 1) {

                try {
                    LoginDAO l = new LoginDAO();
                    ArrayList<Usuario> mp = l.retornaUser(txtusuario.getText(), txtsenha.getText());
                    System.out.println("lista" + mp.size());
                    if (mp.size() > 0) {
                        imagens = mp.get(0).getFoto();
                        imagem = new javax.swing.JLabel();
                        imagem.setText(imagens);
                        idUsuario = mp.get(0).getId();
                        System.out.println("id Usuario " + idUsuario);

                        JOptionPane.showMessageDialog(null, "Olá. Bom trabalho  " + mp.get(0).getNome());
                        new Principal().show();
                        dispose();
                    } else if (mp.size() <= 0) {
                        conta++;
                        JOptionPane.showMessageDialog(null, "Usuário não encontrado");

                        if (conta == 2) {
                            JOptionPane.showMessageDialog(null, "Usuário não autorizado há "
                                    + "utilizar o Sistema.\n\n            O Sistema será finalizado.");
                            dispose();
                        }
                    }
                } catch (SQLException ex) {
                    try {
                        System.out.println(ex);
                    } catch (IndexOutOfBoundsException ex1) {
                        JOptionPane.showMessageDialog(null, "Usuário não encontrado");
                    }
                }

            }

        }


    }//GEN-LAST:event_btnconsultaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        txtsenha.setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Login().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnconsulta;
    private java.awt.Button btnconsulta1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblimagem;
    private javax.swing.JPasswordField txtsenha;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
