/*
 * Login.java
 *
 * Created on 14 de Setembro de 2011, 14:27
 */
package br.com.gecel.view;

import br.com.gecel.control.Conexao;
import br.com.gecel.dao.LoginDAO;
import br.com.gecel.exception.CreateDAOException;
import br.com.gecel.model.entity.Usuario;
import br.com.gecel.relatorio.RelatorioParticipanteAll;
import br.com.gecel.relatorio.RelatorioParticipanteByNascimento;
import java.awt.AWTKeyStroke;
import java.awt.KeyboardFocusManager;
import java.awt.Label;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Familia-Silva
 */
public class Relatorio extends javax.swing.JFrame {

    private Conexao connect;
    public static String mes = null;
    public String imagens = null;

    /**
     * Creates new form Login
     */
    public Relatorio() throws SQLException {
        initComponents();
        enter();
        setResizable(false);

    }

    public void enter() {
// Enter simula tecla Tab
        HashSet conj = new HashSet(getFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS));
        conj.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_ENTER, 0));
        setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, conj);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnconsulta = new java.awt.Button();
        btnconsulta1 = new java.awt.Button();
        cmbMes = new javax.swing.JComboBox();
        cmbConsulta = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Relatório");
        getContentPane().setLayout(null);

        btnconsulta.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnconsulta.setLabel("Imprimir");
        btnconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultaActionPerformed(evt);
            }
        });
        getContentPane().add(btnconsulta);
        btnconsulta.setBounds(10, 130, 80, 30);

        btnconsulta1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnconsulta1.setLabel("Sair");
        btnconsulta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsulta1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnconsulta1);
        btnconsulta1.setBounds(100, 130, 80, 30);

        cmbMes.setMaximumRowCount(4);
        cmbMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        getContentPane().add(cmbMes);
        cmbMes.setBounds(10, 60, 170, 20);

        cmbConsulta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tipo Consulta", "Mês Nascimento", "Todos" }));
        getContentPane().add(cmbConsulta);
        cmbConsulta.setBounds(10, 20, 170, 20);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-200)/2, (screenSize.height-200)/2, 200, 200);
    }// </editor-fold>//GEN-END:initComponents

    private void btnconsulta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsulta1ActionPerformed
// TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnconsulta1ActionPerformed

    private void btnconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultaActionPerformed
        // TODO add your handling code here:
        if (cmbConsulta.getSelectedItem().equals("Tipo Consulta")) {
            JOptionPane.showMessageDialog(null, "Selecione tipo de consulta");
            cmbConsulta.requestFocus();
        } else {



            if (cmbConsulta.getSelectedItem().equals("Mês Nascimento")) {
                if (cmbMes.getSelectedItem().equals("Janeiro")) {
                    mes = "01";
                    System.out.println("mes " + mes);
                } else if (cmbMes.getSelectedItem().equals("Fevereiro")) {
                    mes = "02";
                    System.out.println("mes " + mes);
                } else if (cmbMes.getSelectedItem().equals("Março")) {
                    mes = "03";
                    System.out.println("mes " + mes);
                } else if (cmbMes.getSelectedItem().equals("Abril")) {
                    mes = "04";
                    System.out.println("mes " + mes);
                } else if (cmbMes.getSelectedItem().equals("Maio")) {
                    mes = "05";
                    System.out.println("mes " + mes);
                } else if (cmbMes.getSelectedItem().equals("Junho")) {
                    mes = "06";
                    System.out.println("mes " + mes);
                } else if (cmbMes.getSelectedItem().equals("Julho")) {
                    mes = "07";
                    System.out.println("mes " + mes);
                } else if (cmbMes.getSelectedItem().equals("Agosto")) {
                    mes = "08";
                    System.out.println("mes " + mes);
                } else if (cmbMes.getSelectedItem().equals("Setembro")) {
                    mes = "09";
                    System.out.println("mes " + mes);
                } else if (cmbMes.getSelectedItem().equals("Outubro")) {
                    mes = "10";
                    System.out.println("mes " + mes);
                } else if (cmbMes.getSelectedItem().equals("Novembro")) {
                    mes = "11";
                    System.out.println("mes " + mes);
                } else if (cmbMes.getSelectedItem().equals("Dezembro")) {
                    mes = "12";
                    System.out.println("mes " + mes);
                }

                new RelatorioParticipanteByNascimento();
            } else if (cmbConsulta.getSelectedItem().equals("Todos")) {
                new RelatorioParticipanteAll();
            }
        }
    }//GEN-LAST:event_btnconsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Relatorio().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Relatorio.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnconsulta;
    private java.awt.Button btnconsulta1;
    private javax.swing.JComboBox cmbConsulta;
    public static javax.swing.JComboBox cmbMes;
    // End of variables declaration//GEN-END:variables
}
